#create postgres service with env from .env file and port 5432 exposed

version: '3.6'
services:
  postgres:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  migrator:
    image: tienpvse/k8s-migration:latest
    depends_on:
      - postgres
    restart: no
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    

volumes:
  postgres-data:
